import {
    TELENEUMU_CONTACT as ENV_TELENEUMU_CONTACT,
    TELENEUMU_SUBJECT as ENV_TELENEUMU_SUBJECT
} from '@env'

export const TELENEUMU_CONTACT = ENV_TELENEUMU_CONTACT
export const TELENEUMU_SUBJECT = ENV_TELENEUMU_SUBJECT