import {
    GOV_BR_URI as ENV_GOV_BR_URI,
    FLATICON_URI as ENV_FLATICON_URI,
    BOOTDEY_URI as ENV_BOOTDEY_URI,
    INSTITUTE_URI as ENV_INSTITUTE_URI,
    CONECTESUS_URI as ENV_CONECTESUS_URI,
    API_BASE_URL as ENV_API_BASE_URL,
    API_IBGE_GOV as ENV_API_IBGE_GOV,
    API_POSTAL_CODE_SEARCH as ENV_API_POSTAL_CODE_SEARCH
} from '@env'

export const API_BASE_URL = ENV_API_BASE_URL
export const API_IBGE_GOV = ENV_API_IBGE_GOV
export const API_POSTAL_CODE_SEARCH = ENV_API_POSTAL_CODE_SEARCH
export const GOV_BR_URI = ENV_GOV_BR_URI
export const FLATICON_URI = ENV_FLATICON_URI
export const BOOTDEY_URI = ENV_BOOTDEY_URI
export const INSTITUTE_URI = ENV_INSTITUTE_URI
export const CONECTESUS_URI = ENV_CONECTESUS_URI