require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '12.4'

target 'TeleNeuMu' do
  config = use_native_modules!

  use_react_native!(
    path: config['reactNativePath'],
    # to enable hermes on iOS, change `false` to `true` and then install pods
    :hermes_enabled => false
  )




  target 'TeleNeuMuTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable the next line.
  use_flipper!({'Flipper' => '0.164.0'})

  post_install do |installer|
    react_native_post_install(installer)
    flipper_post_install(installer)
  
    installer.aggregate_targets.each do |aggregate_target|
      aggregate_target.user_project.native_targets.each do |target|
        target.build_configurations.each do |config|
          # Arch selection is needed to work across M1/Intel macs, became necessary when App Check was added
          config.build_settings['OTHER_CPLUSPLUSFLAGS'] = ''
        end
      end
      aggregate_target.user_project.save
    end
    
    installer.pods_project.build_configurations.each do |config|
      config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
    end
    
    __apply_Xcode_12_5_M1_post_install_workaround(installer)
  end
end
