const specialties = [
    'Acupuntura',
    'Alergia e Imunologia',
    'Anestesiologia',
    'Angiologia',
    'Cancerologia',
    'Cardiologia',
    'Cirurgia Cardiovascular',
    'Cirurgia de Mão',
    'Cirurgia de Cabeça e Pescoço',
    'Cirurgia do aparelho digestivo',
    'Cirurgia Geral',
    'Cirurgia Pediátrica',
    'Cirurgia Plástica',
    'Cirurgia Toráxica',
    'Cirurgia Vascular',
    'Clínica Médica',
    'Coloproctologia',
    'Dermatologia',
    'Endocrinologia e Metabolismo',
    'Endoscopia',
    'Gastroenterologia',
    'Genética Médica',
    'Geriatria',
    'Ginecologia e Obstetrícia',
    'Hematologia e Hemoterapia',
    'Homeopatia',
    'Infectologia',
    'Mastologia',
    'Medicina Familiar e Comunitária',
    'Medicina Ocupacional',
    'Medicina de Trânsito',
    'Medicina Esportiva',
    'Medicina Física e Reabilitação',
    'Tratamento intensivo',
    'Medicina legal e perícia médica',
    'Medicina nuclear',
    'Medicina Preventiva e Social',
    'Nefrologia',
    'Neurocirurgia',
    'Neurologia',
    'Nutrilogia',
    'Oftalmologia',
    'Ortopedia e Traumatologia',
    'Otorrinolaringologia',
    'Patologia',
    'Patologia Clínica / Medicina Laboratorial',
    'Pediatria',
    'Pneumologia',
    'Psiquiatria',
    'Radiologia e diagnóstico por imagem',
    'Radioterapia',
    'Reumatologia',
    'Urologia'
]

export default specialties
